spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring?serverTimezone=UTC
    username: root
    password: admin
    driver-class-name:  com.mysql.cj.jdbc.Driver
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml