spring:
  datasource:
    url: jdbc:mysql://192.168.145.128:3306/jpa
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
#    \u662F\u5426\u6267\u884C\u5EFA\u8868
#    hibernate:
#      ddl-auto: update